### ISSUE TITLE
Improve compatibility with things that require asynchronicity

### ISSUE THREAD

**Issue by lencioni** [trotzig/likadan#28]
We have a likadan for a react component that uses `requestAnimationFrame` when it renders to set some state. The snapshot seems to sometimes be taken before this happens, and sometimes after it happens. It would be nice if there was a way to ensure that the snapshot is always taken after the `requestAnimationFrame`.

Jasmine solves this by having the function take a callback argument and requiring the spec to call it when it is done. I wonder if a similar technique would work for us here.

**Comment by lencioni** [comment]
I'm working on this and I think that am pretty close but won't have time to finish it up today.

**Comment by trotzig** [comment]
Because of the communication between the Ruby layer and the JS (browser) layer, this is a little bit tricky. Though not impossible. The way I imagine this being implemented is by allowing `likadan.renderCurrent()` to return something that tells the Ruby thread to pause and try again in a short while. Was that your idea too @lencioni?

**Comment by lencioni** [comment]
Not exactly. I'm implementing this using a similar strategy to how Jasmine does it. WebDriver has an `execute_async_script` function that works like its `execute_script` but it injects a callback argument that it waits to be called before proceeding. You can pass information to the callback and use it in Rubyland, so I plan on using that along with promises in the JS to make it all work together.

**Comment by trotzig** [comment]
That's a lot better!
